// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_lists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDataListsByKind = `-- name: CountDataListsByKind :one
SELECT count(*) FROM data_lists
WHERE ($1::text = '' OR kind = $1::text)
`

func (q *Queries) CountDataListsByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, countDataListsByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDataList = `-- name: CreateDataList :one
INSERT INTO data_lists (label, kind, key, value, item_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, label, kind, key, value, item_order, create_time, update_time
`

type CreateDataListParams struct {
	Label     string `json:"label"`
	Kind      string `json:"kind"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	ItemOrder int32  `json:"item_order"`
}

func (q *Queries) CreateDataList(ctx context.Context, arg CreateDataListParams) (*DataList, error) {
	row := q.db.QueryRow(ctx, createDataList,
		arg.Label,
		arg.Kind,
		arg.Key,
		arg.Value,
		arg.ItemOrder,
	)
	var i DataList
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Kind,
		&i.Key,
		&i.Value,
		&i.ItemOrder,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return &i, err
}

const deleteDataList = `-- name: DeleteDataList :execrows
DELETE FROM data_lists WHERE id = $1
`

func (q *Queries) DeleteDataList(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDataList, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDataList = `-- name: GetDataList :one
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists WHERE id = $1
`

func (q *Queries) GetDataList(ctx context.Context, id int64) (*DataList, error) {
	row := q.db.QueryRow(ctx, getDataList, id)
	var i DataList
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Kind,
		&i.Key,
		&i.Value,
		&i.ItemOrder,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return &i, err
}

const listDataListSortData = `-- name: ListDataListSortData :many
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists WHERE kind = $1 ORDER BY item_order DESC
`

func (q *Queries) ListDataListSortData(ctx context.Context, kind string) ([]*DataList, error) {
	rows, err := q.db.Query(ctx, listDataListSortData, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DataList
	for rows.Next() {
		var i DataList
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.ItemOrder,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataLists = `-- name: ListDataLists :many
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists
WHERE ($1::text = '' OR kind = $1::text)
ORDER BY id
`

func (q *Queries) ListDataLists(ctx context.Context, kind string) ([]*DataList, error) {
	rows, err := q.db.Query(ctx, listDataLists, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DataList
	for rows.Next() {
		var i DataList
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.ItemOrder,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataListsByKindPage = `-- name: ListDataListsByKindPage :many
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists
WHERE ($1::text = '' OR kind = $1::text)
ORDER BY id
LIMIT $3::integer OFFSET $2::integer
`

type ListDataListsByKindPageParams struct {
	Kind       string `json:"kind"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListDataListsByKindPage(ctx context.Context, arg ListDataListsByKindPageParams) ([]*DataList, error) {
	rows, err := q.db.Query(ctx, listDataListsByKindPage, arg.Kind, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DataList
	for rows.Next() {
		var i DataList
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.ItemOrder,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataListsByKinds = `-- name: ListDataListsByKinds :many
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists
WHERE kind = ANY($1::text[])
ORDER BY id
`

func (q *Queries) ListDataListsByKinds(ctx context.Context, kinds []string) ([]*DataList, error) {
	rows, err := q.db.Query(ctx, listDataListsByKinds, kinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DataList
	for rows.Next() {
		var i DataList
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.ItemOrder,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataListsByKindsAsc = `-- name: ListDataListsByKindsAsc :many
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists
WHERE kind = ANY($1::text[])
ORDER BY item_order ASC
`

func (q *Queries) ListDataListsByKindsAsc(ctx context.Context, kinds []string) ([]*DataList, error) {
	rows, err := q.db.Query(ctx, listDataListsByKindsAsc, kinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DataList
	for rows.Next() {
		var i DataList
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.ItemOrder,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataListsByKindsDesc = `-- name: ListDataListsByKindsDesc :many
SELECT id, label, kind, key, value, item_order, create_time, update_time
FROM data_lists
WHERE kind = ANY($1::text[])
ORDER BY item_order DESC
`

func (q *Queries) ListDataListsByKindsDesc(ctx context.Context, kinds []string) ([]*DataList, error) {
	rows, err := q.db.Query(ctx, listDataListsByKindsDesc, kinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DataList
	for rows.Next() {
		var i DataList
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.ItemOrder,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataList = `-- name: UpdateDataList :one
UPDATE data_lists
SET key = $1, value = $2,
    item_order = COALESCE($3::integer, item_order),
    update_time = now()
WHERE id = $4
RETURNING id, label, kind, key, value, item_order, create_time, update_time
`

type UpdateDataListParams struct {
	Key       string      `json:"key"`
	Value     string      `json:"value"`
	ItemOrder pgtype.Int4 `json:"item_order"`
	ID        int64       `json:"id"`
}

func (q *Queries) UpdateDataList(ctx context.Context, arg UpdateDataListParams) (*DataList, error) {
	row := q.db.QueryRow(ctx, updateDataList,
		arg.Key,
		arg.Value,
		arg.ItemOrder,
		arg.ID,
	)
	var i DataList
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Kind,
		&i.Key,
		&i.Value,
		&i.ItemOrder,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return &i, err
}

const updateDataListOrder = `-- name: UpdateDataListOrder :execrows
UPDATE data_lists SET item_order = $2, update_time = now() WHERE id = $1
`

type UpdateDataListOrderParams struct {
	ID        int64 `json:"id"`
	ItemOrder int32 `json:"item_order"`
}

func (q *Queries) UpdateDataListOrder(ctx context.Context, arg UpdateDataListOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDataListOrder, arg.ID, arg.ItemOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
