// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountDataListsByKind(ctx context.Context, kind string) (int64, error)
	CreateDataList(ctx context.Context, arg CreateDataListParams) (*DataList, error)
	CreateSiteConfig(ctx context.Context, arg CreateSiteConfigParams) (*SiteConfig, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteDataList(ctx context.Context, id int64) (int64, error)
	DeleteSiteConfig(ctx context.Context, id int64) (int64, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetDataList(ctx context.Context, id int64) (*DataList, error)
	GetSiteConfig(ctx context.Context, id int64) (*SiteConfig, error)
	GetSiteConfigByName(ctx context.Context, name string) (*SiteConfig, error)
	GetUser(ctx context.Context, id int64) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	ListDataListSortData(ctx context.Context, kind string) ([]*DataList, error)
	ListDataLists(ctx context.Context, kind string) ([]*DataList, error)
	ListDataListsByKindPage(ctx context.Context, arg ListDataListsByKindPageParams) ([]*DataList, error)
	ListDataListsByKinds(ctx context.Context, kinds []string) ([]*DataList, error)
	ListDataListsByKindsAsc(ctx context.Context, kinds []string) ([]*DataList, error)
	ListDataListsByKindsDesc(ctx context.Context, kinds []string) ([]*DataList, error)
	ListSiteConfigNames(ctx context.Context) ([]string, error)
	ListSiteConfigs(ctx context.Context) ([]*SiteConfig, error)
	ListUsers(ctx context.Context) ([]*User, error)
	UpdateDataList(ctx context.Context, arg UpdateDataListParams) (*DataList, error)
	UpdateDataListOrder(ctx context.Context, arg UpdateDataListOrderParams) (int64, error)
	UpdateSiteConfig(ctx context.Context, arg UpdateSiteConfigParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
