// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_configs.sql

package sqlc

import (
	"context"
)

const createSiteConfig = `-- name: CreateSiteConfig :one
INSERT INTO site_configs (name, config)
VALUES ($1, $2)
RETURNING id, name, config, create_time, update_time
`

type CreateSiteConfigParams struct {
	Name   string `json:"name"`
	Config string `json:"config"`
}

func (q *Queries) CreateSiteConfig(ctx context.Context, arg CreateSiteConfigParams) (*SiteConfig, error) {
	row := q.db.QueryRow(ctx, createSiteConfig, arg.Name, arg.Config)
	var i SiteConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return &i, err
}

const deleteSiteConfig = `-- name: DeleteSiteConfig :execrows
DELETE FROM site_configs WHERE id = $1
`

func (q *Queries) DeleteSiteConfig(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSiteConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSiteConfig = `-- name: GetSiteConfig :one
SELECT id, name, config, create_time, update_time FROM site_configs WHERE id = $1
`

func (q *Queries) GetSiteConfig(ctx context.Context, id int64) (*SiteConfig, error) {
	row := q.db.QueryRow(ctx, getSiteConfig, id)
	var i SiteConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return &i, err
}

const getSiteConfigByName = `-- name: GetSiteConfigByName :one
SELECT id, name, config, create_time, update_time FROM site_configs WHERE name = $1
`

func (q *Queries) GetSiteConfigByName(ctx context.Context, name string) (*SiteConfig, error) {
	row := q.db.QueryRow(ctx, getSiteConfigByName, name)
	var i SiteConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return &i, err
}

const listSiteConfigNames = `-- name: ListSiteConfigNames :many
SELECT name FROM site_configs ORDER BY name
`

func (q *Queries) ListSiteConfigNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSiteConfigNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteConfigs = `-- name: ListSiteConfigs :many
SELECT id, name, config, create_time, update_time FROM site_configs ORDER BY id
`

func (q *Queries) ListSiteConfigs(ctx context.Context) ([]*SiteConfig, error) {
	rows, err := q.db.Query(ctx, listSiteConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SiteConfig
	for rows.Next() {
		var i SiteConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteConfig = `-- name: UpdateSiteConfig :execrows
UPDATE site_configs
SET config = $2, update_time = now()
WHERE name = $1
`

type UpdateSiteConfigParams struct {
	Name   string `json:"name"`
	Config string `json:"config"`
}

func (q *Queries) UpdateSiteConfig(ctx context.Context, arg UpdateSiteConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSiteConfig, arg.Name, arg.Config)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
