// Code generated by loom. DO NOT EDIT.

package cmd_app

import (
	"github.com/Xwudao/loom"
	"github.com/Xwudao/neter-template/internal/system"
	"github.com/Xwudao/neter-template/pkg/config"
	"github.com/Xwudao/neter-template/pkg/logger"
)

// InitCmd builds *InitApp from the graph declared by initAppGraph.
func InitCmd() (*InitApp, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	initApp := NewInitApp()

	return initApp, lifecycle, nil
}

// MigrateCmd builds *MigrateApp from the graph declared by migrateAppGraph.
func MigrateCmd() (*MigrateApp, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	appContext := system.NewAppContext()

	koanf, err := config.NewKoanf()
	if err != nil {
		return nil, nil, err
	}

	sugaredLogger, err := logger.NewLogger(koanf)
	if err != nil {
		return nil, nil, err
	}

	migrateApp := NewMigrateApp(appContext, koanf, sugaredLogger)

	return migrateApp, lifecycle, nil
}
