// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd_app

import (
	"go-kitboxpro/internal/system"
	"go-kitboxpro/pkg/config"
	"go-kitboxpro/pkg/logger"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func MigrateCmd() (*MigrateApp, func(), error) {
	appContext := system.NewAppContext()
	koanf, err := config.NewKoanf()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, err := logger.NewLogger(koanf)
	if err != nil {
		return nil, nil, err
	}
	migrateApp := NewMigrateApp(appContext, koanf, sugaredLogger)
	return migrateApp, func() {
	}, nil
}

func InitCmd() (*InitApp, func(), error) {
	initApp := NewInitApp()
	return initApp, func() {
	}, nil
}
