// Code generated by MockGen. DO NOT EDIT.
// Source: internal/biz/site_config_biz.go
//
// Generated by this command:
//
//	mockgen -source=internal/biz/site_config_biz.go -destination=internal/biz/mocks/mock_site_config_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ent "github.com/Xwudao/neter-template/internal/data/ent"
	params "github.com/Xwudao/neter-template/internal/domain/params"
	gomock "go.uber.org/mock/gomock"
)

// MockSiteConfigRepository is a mock of SiteConfigRepository interface.
type MockSiteConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSiteConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockSiteConfigRepositoryMockRecorder is the mock recorder for MockSiteConfigRepository.
type MockSiteConfigRepositoryMockRecorder struct {
	mock *MockSiteConfigRepository
}

// NewMockSiteConfigRepository creates a new mock instance.
func NewMockSiteConfigRepository(ctrl *gomock.Controller) *MockSiteConfigRepository {
	mock := &MockSiteConfigRepository{ctrl: ctrl}
	mock.recorder = &MockSiteConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteConfigRepository) EXPECT() *MockSiteConfigRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSiteConfigRepository) Create(ctx context.Context, p *params.CreateSiteConfigParams) (*ent.SiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(*ent.SiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSiteConfigRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSiteConfigRepository)(nil).Create), ctx, p)
}

// DeleteByID mocks base method.
func (m *MockSiteConfigRepository) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockSiteConfigRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockSiteConfigRepository)(nil).DeleteByID), ctx, id)
}

// GetAll mocks base method.
func (m *MockSiteConfigRepository) GetAll(ctx context.Context) ([]*ent.SiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*ent.SiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSiteConfigRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSiteConfigRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockSiteConfigRepository) GetByID(ctx context.Context, id int64) (*ent.SiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*ent.SiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSiteConfigRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSiteConfigRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockSiteConfigRepository) GetByName(ctx context.Context, name string) (*ent.SiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*ent.SiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSiteConfigRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSiteConfigRepository)(nil).GetByName), ctx, name)
}

// GetNames mocks base method.
func (m *MockSiteConfigRepository) GetNames(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNames", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNames indicates an expected call of GetNames.
func (mr *MockSiteConfigRepositoryMockRecorder) GetNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNames", reflect.TypeOf((*MockSiteConfigRepository)(nil).GetNames), ctx)
}

// Update mocks base method.
func (m *MockSiteConfigRepository) Update(ctx context.Context, p *params.UpdateSiteConfigParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSiteConfigRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSiteConfigRepository)(nil).Update), ctx, p)
}
