// Code generated by MockGen. DO NOT EDIT.
// Source: internal/biz/user_biz_iface.go
//
// Generated by this command:
//
//	mockgen -source=internal/biz/user_biz_iface.go -destination=internal/biz/mocks/mock_user_biz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sqlc "github.com/Xwudao/neter-template/internal/data/sqlc"
	params "github.com/Xwudao/neter-template/internal/domain/params"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserBizIface is a mock of UserBizIface interface.
type MockUserBizIface struct {
	ctrl     *gomock.Controller
	recorder *MockUserBizIfaceMockRecorder
	isgomock struct{}
}

// MockUserBizIfaceMockRecorder is the mock recorder for MockUserBizIface.
type MockUserBizIfaceMockRecorder struct {
	mock *MockUserBizIface
}

// NewMockUserBizIface creates a new mock instance.
func NewMockUserBizIface(ctrl *gomock.Controller) *MockUserBizIface {
	mock := &MockUserBizIface{ctrl: ctrl}
	mock.recorder = &MockUserBizIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserBizIface) EXPECT() *MockUserBizIfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserBizIface) Create(ctx context.Context, p *params.CreateUserParams) (*sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(*sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserBizIfaceMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserBizIface)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockUserBizIface) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserBizIfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserBizIface)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockUserBizIface) Get(ctx context.Context, id int64) (*sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserBizIfaceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserBizIface)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockUserBizIface) GetAll(ctx context.Context) ([]*sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserBizIfaceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserBizIface)(nil).GetAll), ctx)
}

// GetBy mocks base method.
func (m *MockUserBizIface) GetBy(ctx context.Context, p *params.GetUserByParams) (*sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBy", ctx, p)
	ret0, _ := ret[0].(*sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBy indicates an expected call of GetBy.
func (mr *MockUserBizIfaceMockRecorder) GetBy(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBy", reflect.TypeOf((*MockUserBizIface)(nil).GetBy), ctx, p)
}

// Login mocks base method.
func (m *MockUserBizIface) Login(ctx context.Context, p *params.UserLoginParams) (*sqlc.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, p)
	ret0, _ := ret[0].(*sqlc.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockUserBizIfaceMockRecorder) Login(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserBizIface)(nil).Login), ctx, p)
}
