// Code generated by MockGen. DO NOT EDIT.
// Source: ../data_list_biz_iface.go
//
// Generated by this command:
//
//	mockgen -source=../data_list_biz_iface.go -destination=mock_data_list_biz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ent "github.com/Xwudao/neter-template/internal/data/ent"
	params "github.com/Xwudao/neter-template/internal/domain/params"
	gomock "go.uber.org/mock/gomock"
)

// MockDataListBizIface is a mock of DataListBizIface interface.
type MockDataListBizIface struct {
	ctrl     *gomock.Controller
	recorder *MockDataListBizIfaceMockRecorder
	isgomock struct{}
}

// MockDataListBizIfaceMockRecorder is the mock recorder for MockDataListBizIface.
type MockDataListBizIfaceMockRecorder struct {
	mock *MockDataListBizIface
}

// NewMockDataListBizIface creates a new mock instance.
func NewMockDataListBizIface(ctrl *gomock.Controller) *MockDataListBizIface {
	mock := &MockDataListBizIface{ctrl: ctrl}
	mock.recorder = &MockDataListBizIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataListBizIface) EXPECT() *MockDataListBizIfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataListBizIface) Create(ctx context.Context, p *params.CreateDataListParams) (*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDataListBizIfaceMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataListBizIface)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockDataListBizIface) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataListBizIfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataListBizIface)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockDataListBizIface) Get(ctx context.Context, id int64) (*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDataListBizIfaceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDataListBizIface)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockDataListBizIface) GetAll(ctx context.Context) ([]*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDataListBizIfaceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDataListBizIface)(nil).GetAll), ctx)
}

// GetAllByKinds mocks base method.
func (m *MockDataListBizIface) GetAllByKinds(ctx context.Context, p *params.GetAllDataListByKindsParams) ([]*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByKinds", ctx, p)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByKinds indicates an expected call of GetAllByKinds.
func (mr *MockDataListBizIfaceMockRecorder) GetAllByKinds(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByKinds", reflect.TypeOf((*MockDataListBizIface)(nil).GetAllByKinds), ctx, p)
}

// GetSortData mocks base method.
func (m *MockDataListBizIface) GetSortData(ctx context.Context, p *params.GetDataListSortDataParams) ([]*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSortData", ctx, p)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSortData indicates an expected call of GetSortData.
func (mr *MockDataListBizIfaceMockRecorder) GetSortData(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSortData", reflect.TypeOf((*MockDataListBizIface)(nil).GetSortData), ctx, p)
}

// ListByKind mocks base method.
func (m *MockDataListBizIface) ListByKind(ctx context.Context, p *params.ListDataByKindParams) ([]*ent.DataList, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByKind", ctx, p)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByKind indicates an expected call of ListByKind.
func (mr *MockDataListBizIfaceMockRecorder) ListByKind(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByKind", reflect.TypeOf((*MockDataListBizIface)(nil).ListByKind), ctx, p)
}

// Update mocks base method.
func (m *MockDataListBizIface) Update(ctx context.Context, p *params.UpdateDataListParams) (*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDataListBizIfaceMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataListBizIface)(nil).Update), ctx, p)
}

// UpdateOrder mocks base method.
func (m *MockDataListBizIface) UpdateOrder(ctx context.Context, p *params.ItemOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockDataListBizIfaceMockRecorder) UpdateOrder(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockDataListBizIface)(nil).UpdateOrder), ctx, p)
}
