// Code generated by MockGen. DO NOT EDIT.
// Source: ../html_help_biz_iface.go
//
// Generated by this command:
//
//	mockgen -source=../html_help_biz_iface.go -destination=mock_html_help_biz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
	models "github.com/Xwudao/neter-template/internal/domain/models"
)

// MockHtmlHelpBizIface is a mock of HtmlHelpBizIface interface.
type MockHtmlHelpBizIface struct {
	ctrl     *gomock.Controller
	recorder *MockHtmlHelpBizIfaceMockRecorder
	isgomock struct{}
}

// MockHtmlHelpBizIfaceMockRecorder is the mock recorder for MockHtmlHelpBizIface.
type MockHtmlHelpBizIfaceMockRecorder struct {
	mock *MockHtmlHelpBizIface
}

// NewMockHtmlHelpBizIface creates a new mock instance.
func NewMockHtmlHelpBizIface(ctrl *gomock.Controller) *MockHtmlHelpBizIface {
	mock := &MockHtmlHelpBizIface{ctrl: ctrl}
	mock.recorder = &MockHtmlHelpBizIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHtmlHelpBizIface) EXPECT() *MockHtmlHelpBizIfaceMockRecorder {
	return m.recorder
}

// BuildBase mocks base method.
func (m *MockHtmlHelpBizIface) BuildBase(c *gin.Context) (*models.HtmlBaseModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBase", c)
	ret0, _ := ret[0].(*models.HtmlBaseModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildBase indicates an expected call of BuildBase.
func (mr *MockHtmlHelpBizIfaceMockRecorder) BuildBase(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBase", reflect.TypeOf((*MockHtmlHelpBizIface)(nil).BuildBase), c)
}

// BuildIndexMap mocks base method.
func (m *MockHtmlHelpBizIface) BuildIndexMap(c *gin.Context) (*models.IndexHtmlModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildIndexMap", c)
	ret0, _ := ret[0].(*models.IndexHtmlModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildIndexMap indicates an expected call of BuildIndexMap.
func (mr *MockHtmlHelpBizIfaceMockRecorder) BuildIndexMap(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildIndexMap", reflect.TypeOf((*MockHtmlHelpBizIface)(nil).BuildIndexMap), c)
}
