// Code generated by MockGen. DO NOT EDIT.
// Source: ../site_help_biz_iface.go
//
// Generated by this command:
//
//	mockgen -source=../site_help_biz_iface.go -destination=mock_site_help_biz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSiteHelpBizIface is a mock of SiteHelpBizIface interface.
type MockSiteHelpBizIface struct {
	ctrl     *gomock.Controller
	recorder *MockSiteHelpBizIfaceMockRecorder
	isgomock struct{}
}

// MockSiteHelpBizIfaceMockRecorder is the mock recorder for MockSiteHelpBizIface.
type MockSiteHelpBizIfaceMockRecorder struct {
	mock *MockSiteHelpBizIface
}

// NewMockSiteHelpBizIface creates a new mock instance.
func NewMockSiteHelpBizIface(ctrl *gomock.Controller) *MockSiteHelpBizIface {
	mock := &MockSiteHelpBizIface{ctrl: ctrl}
	mock.recorder = &MockSiteHelpBizIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteHelpBizIface) EXPECT() *MockSiteHelpBizIfaceMockRecorder {
	return m.recorder
}

// GenerateSiteMap mocks base method.
func (m *MockSiteHelpBizIface) GenerateSiteMap(ctx context.Context, mapPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSiteMap", ctx, mapPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateSiteMap indicates an expected call of GenerateSiteMap.
func (mr *MockSiteHelpBizIfaceMockRecorder) GenerateSiteMap(ctx, mapPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSiteMap", reflect.TypeOf((*MockSiteHelpBizIface)(nil).GenerateSiteMap), ctx, mapPath)
}
