// Code generated by MockGen. DO NOT EDIT.
// Source: ../data_list_biz.go
//
// Generated by this command:
//
//	mockgen -source=../data_list_biz.go -destination=mock_data_list_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ent "github.com/Xwudao/neter-template/internal/data/ent"
	params "github.com/Xwudao/neter-template/internal/domain/params"
	gomock "go.uber.org/mock/gomock"
)

// MockDataListRepository is a mock of DataListRepository interface.
type MockDataListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDataListRepositoryMockRecorder
	isgomock struct{}
}

// MockDataListRepositoryMockRecorder is the mock recorder for MockDataListRepository.
type MockDataListRepositoryMockRecorder struct {
	mock *MockDataListRepository
}

// NewMockDataListRepository creates a new mock instance.
func NewMockDataListRepository(ctrl *gomock.Controller) *MockDataListRepository {
	mock := &MockDataListRepository{ctrl: ctrl}
	mock.recorder = &MockDataListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataListRepository) EXPECT() *MockDataListRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataListRepository) Create(ctx context.Context, p *params.CreateDataListParams) (*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDataListRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataListRepository)(nil).Create), ctx, p)
}

// DeleteByID mocks base method.
func (m *MockDataListRepository) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockDataListRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockDataListRepository)(nil).DeleteByID), ctx, id)
}

// GetAll mocks base method.
func (m *MockDataListRepository) GetAll(ctx context.Context) ([]*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDataListRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDataListRepository)(nil).GetAll), ctx)
}

// GetAllByKinds mocks base method.
func (m *MockDataListRepository) GetAllByKinds(ctx context.Context, kinds *params.GetAllDataListByKindsParams) ([]*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByKinds", ctx, kinds)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByKinds indicates an expected call of GetAllByKinds.
func (mr *MockDataListRepositoryMockRecorder) GetAllByKinds(ctx, kinds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByKinds", reflect.TypeOf((*MockDataListRepository)(nil).GetAllByKinds), ctx, kinds)
}

// GetByID mocks base method.
func (m *MockDataListRepository) GetByID(ctx context.Context, id int64) (*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDataListRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDataListRepository)(nil).GetByID), ctx, id)
}

// GetSortData mocks base method.
func (m *MockDataListRepository) GetSortData(ctx context.Context, p *params.GetDataListSortDataParams) ([]*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSortData", ctx, p)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSortData indicates an expected call of GetSortData.
func (mr *MockDataListRepositoryMockRecorder) GetSortData(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSortData", reflect.TypeOf((*MockDataListRepository)(nil).GetSortData), ctx, p)
}

// ListByKind mocks base method.
func (m *MockDataListRepository) ListByKind(ctx context.Context, p *params.ListDataByKindParams) ([]*ent.DataList, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByKind", ctx, p)
	ret0, _ := ret[0].([]*ent.DataList)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByKind indicates an expected call of ListByKind.
func (mr *MockDataListRepositoryMockRecorder) ListByKind(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByKind", reflect.TypeOf((*MockDataListRepository)(nil).ListByKind), ctx, p)
}

// Update mocks base method.
func (m *MockDataListRepository) Update(ctx context.Context, p *params.UpdateDataListParams) (*ent.DataList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(*ent.DataList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDataListRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataListRepository)(nil).Update), ctx, p)
}

// UpdateOrder mocks base method.
func (m *MockDataListRepository) UpdateOrder(ctx context.Context, p *params.ItemOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockDataListRepositoryMockRecorder) UpdateOrder(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockDataListRepository)(nil).UpdateOrder), ctx, p)
}
