// Code generated by MockGen. DO NOT EDIT.
// Source: internal/biz/site_config_biz_iface.go
//
// Generated by this command:
//
//	mockgen -source=internal/biz/site_config_biz_iface.go -destination=internal/biz/mocks/mock_site_config_biz.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sqlc "github.com/Xwudao/neter-template/internal/data/sqlc"
	params "github.com/Xwudao/neter-template/internal/domain/params"
	enum "github.com/Xwudao/neter-template/pkg/enum"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSiteConfigBizIface is a mock of SiteConfigBizIface interface.
type MockSiteConfigBizIface struct {
	ctrl     *gomock.Controller
	recorder *MockSiteConfigBizIfaceMockRecorder
	isgomock struct{}
}

// MockSiteConfigBizIfaceMockRecorder is the mock recorder for MockSiteConfigBizIface.
type MockSiteConfigBizIfaceMockRecorder struct {
	mock *MockSiteConfigBizIface
}

// NewMockSiteConfigBizIface creates a new mock instance.
func NewMockSiteConfigBizIface(ctrl *gomock.Controller) *MockSiteConfigBizIface {
	mock := &MockSiteConfigBizIface{ctrl: ctrl}
	mock.recorder = &MockSiteConfigBizIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteConfigBizIface) EXPECT() *MockSiteConfigBizIfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSiteConfigBizIface) Create(ctx context.Context, p *params.CreateSiteConfigParams) (*sqlc.SiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(*sqlc.SiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSiteConfigBizIfaceMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSiteConfigBizIface)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockSiteConfigBizIface) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSiteConfigBizIfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSiteConfigBizIface)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockSiteConfigBizIface) Get(ctx context.Context, id int64) (*sqlc.SiteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*sqlc.SiteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSiteConfigBizIfaceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSiteConfigBizIface)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockSiteConfigBizIface) GetAll(ctx context.Context, isAdmin bool) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, isAdmin)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSiteConfigBizIfaceMockRecorder) GetAll(ctx, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSiteConfigBizIface)(nil).GetAll), ctx, isAdmin)
}

// GetConfig mocks base method.
func (m *MockSiteConfigBizIface) GetConfig(key enum.ConfigKey, target any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", key, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockSiteConfigBizIfaceMockRecorder) GetConfig(key, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockSiteConfigBizIface)(nil).GetConfig), key, target)
}

// Init mocks base method.
func (m *MockSiteConfigBizIface) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockSiteConfigBizIfaceMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockSiteConfigBizIface)(nil).Init))
}

// UpdateConfig mocks base method.
func (m *MockSiteConfigBizIface) UpdateConfig(ctx context.Context, config *params.UpdateSiteConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockSiteConfigBizIfaceMockRecorder) UpdateConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockSiteConfigBizIface)(nil).UpdateConfig), ctx, config)
}
