app:
  port: 8080
  mode: debug

log:
  level: debug
  format: json
  linkName: current.log
  path: ./logs



jwt:
  secret: "secret"


cors:
  allowOrigin:
    - http://localhost:*
    - http://127.0.0.1:*
  allowCredentials: true
  maxAge: 24h