app:
  mode: debug
  port: 8080
  pprof: false
  host: true
cors:
  allowCredentials: true
  allowOrigin:
    - localhost
    - 127.0.0.1
  maxAge: 24h
db:
  database: neter
  host: 127.0.0.1
  username: postgres
  password: postgres
  port: 5432
jwt:
  secret: thisstringmustbeverylongandrandom
  expire: 24h
  issuer: neter
log:
  format: text
  level: debug
  linkName: current.log
  path: ./logs

redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
  prefix: ""
