app:
  port: 8080
  mode: debug

log:
  level: debug
  format: json
  linkName: current.log
  path: ./logs

db:
  dialect: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: ent-demo
  devDsn: mysql://root:root@:3306/dev-ent

jwt:
  secret: "secret"


cors:
  allowOrigin:
    - http://localhost:*
    - http://127.0.0.1:*
  allowCredentials: true
  maxAge: 24h

#host := conf.String("mail.host")
#	port := conf.Int("mail.port")
#	username := conf.String("mail.username")
#	password := conf.String("mail.password")
#
#	keepAlive := conf.Bool("mail.keepAlive")
#	connectTimeout := conf.Duration("mail.connectTimeout")
#	sendTimeout := conf.Duration("mail.sendTimeout")

mail:
  from: xx
  host: xx
  port: xx
  username: xx
  password: xx
  keepAlive: true,
  connectTimeout: 10s
  sendTimeout: 10s
