// Code generated by loom. DO NOT EDIT.

package main

import (
	"context"
	"errors"

	"github.com/Xwudao/loom"
	"github.com/Xwudao/neter-template/internal/biz"
	"github.com/Xwudao/neter-template/internal/cmd"
	"github.com/Xwudao/neter-template/internal/cmd_app"
	"github.com/Xwudao/neter-template/internal/cron"
	"github.com/Xwudao/neter-template/internal/data"
	"github.com/Xwudao/neter-template/internal/routes"
	"github.com/Xwudao/neter-template/internal/routes/v1"
	"github.com/Xwudao/neter-template/internal/system"
	"github.com/Xwudao/neter-template/pkg/config"
	"github.com/Xwudao/neter-template/pkg/logger"
	"github.com/Xwudao/neter-template/pkg/utils/jwt"
)

// mainApp builds *cmd.MainApp from the graph declared by mainAppGraph.
func mainApp() (*cmd.MainApp, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	koanf, err := config.NewKoanf()
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	sugaredLogger, err := logger.NewLogger(koanf)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	zapWriter := logger.NewZapWriter(sugaredLogger)

	jwtConfig, err := config.NewJwtConfigData(koanf)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	client := jwt.NewClient(jwtConfig)

	appContext := system.NewAppContext()

	dbConfig, err := config.NewDBConfig(koanf)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	dataData, dataDataCleanup, err := data.NewData(dbConfig, koanf, sugaredLogger)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}
	lifecycle.AddCleanup(func(ctx context.Context) error {
		dataDataCleanup()
		return nil
	})

	userRepository := data.NewUserRepository(appContext, dataData)

	seoBizBiz := biz.NewSeoBizBiz(sugaredLogger, appContext)

	engine, err := routes.NewEngine(zapWriter, client, userRepository, koanf, seoBizBiz, sugaredLogger)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	cronCron, err := cron.NewCron(sugaredLogger)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	userBiz := biz.NewUserBiz(sugaredLogger, userRepository, client, appContext)

	userRoute := v1.NewUserRoute(userBiz, koanf)

	siteConfigRepository := data.NewSiteConfigRepository(appContext, dataData)

	siteConfigBiz := biz.NewSiteConfigBiz(sugaredLogger, siteConfigRepository, appContext)

	siteHelpBiz := biz.NewSiteHelpBiz(sugaredLogger, siteConfigBiz, appContext)

	siteConfigRoute := v1.NewSiteConfigRoute(siteConfigBiz, siteHelpBiz, sugaredLogger, koanf)

	dataListRepository := data.NewDataListRepository(appContext, dataData)

	dataListBiz := biz.NewDataListBiz(sugaredLogger, dataListRepository, appContext)

	dataListRoute := v1.NewDataListRoute(dataListBiz, sugaredLogger, koanf)

	routeRegistry := routes.NewRouteRegistry(userRoute, siteConfigRoute, dataListRoute)

	httpEngine, err := routes.NewHttpEngine(engine, koanf, sugaredLogger, appContext, cronCron, routeRegistry, lifecycle)
	if err != nil {
		return nil, nil, errors.Join(err, lifecycle.Rollback(context.Background()))
	}

	initSystem := system.NewInitSystem(koanf)

	systemInitBiz := biz.NewSystemInitBiz(sugaredLogger, userRepository, appContext)

	migrateApp := cmd_app.NewMigrateApp(appContext, koanf, sugaredLogger)

	cmdMainApp := cmd.NewMainApp(httpEngine, sugaredLogger, koanf, cronCron, initSystem, systemInitBiz, siteConfigBiz, migrateApp)

	return cmdMainApp, lifecycle, nil
}
