// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Xwudao/neter-template/internal/biz"
	"github.com/Xwudao/neter-template/internal/cmd"
	"github.com/Xwudao/neter-template/internal/core"
	"github.com/Xwudao/neter-template/internal/routes"
	"github.com/Xwudao/neter-template/internal/routes/v1"
	"github.com/Xwudao/neter-template/pkg/config"
	"github.com/Xwudao/neter-template/pkg/logger"
	"github.com/Xwudao/neter-template/pkg/utils/cron"
	"github.com/Xwudao/neter-template/pkg/utils/jwt"
)

// Injectors from wire.go:

func mainApp() (*cmd.MainApp, func(), error) {
	koanf, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, err := logger.NewLogger(koanf)
	if err != nil {
		return nil, nil, err
	}
	engine := routes.NewEngine(koanf, sugaredLogger)
	client := jwt.NewClient(koanf)
	homeBiz := biz.NewHomeBiz()
	homeRoute := v1.NewHomeRoute(engine, client, koanf, homeBiz)
	httpEngine, err := routes.NewHttpEngine(engine, koanf, sugaredLogger, homeRoute)
	if err != nil {
		return nil, nil, err
	}
	cronCron := cron.NewCron(sugaredLogger)
	initSystem := core.NewInitSystem(cronCron)
	cmdMainApp, cleanup := cmd.NewMainApp(httpEngine, cronCron, initSystem)
	return cmdMainApp, func() {
		cleanup()
	}, nil
}
