// Code generated by loom. DO NOT EDIT.

package core

import (
	"github.com/Xwudao/loom"
	"github.com/Xwudao/neter-template/internal/system"
	"github.com/Xwudao/neter-template/pkg/config"
	"github.com/Xwudao/neter-template/pkg/logger"
)

// TestApp builds *Test from the graph declared by testAppGraph.
func TestApp() (*Test, *loom.Lifecycle, error) {
	lifecycle := loom.NewLifecycle()

	sugaredLogger, err := logger.NewTestLogger()
	if err != nil {
		return nil, nil, err
	}

	appContext := system.NewTestAppContext()

	koanf, err := config.NewTestConfig()
	if err != nil {
		return nil, nil, err
	}

	test := NewTestApp(sugaredLogger, appContext, koanf)

	return test, lifecycle, nil
}
