// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"go-kitboxpro/internal/system"
	"go-kitboxpro/pkg/config"
	"go-kitboxpro/pkg/logger"
)

// Injectors from wire.go:

func TestApp() (*Test, func(), error) {
	sugaredLogger, err := logger.NewTestLogger()
	if err != nil {
		return nil, nil, err
	}
	appContext := system.NewTestAppContext()
	koanf, err := config.NewTestConfig()
	if err != nil {
		return nil, nil, err
	}
	test := NewTestApp(sugaredLogger, appContext, koanf)
	return test, func() {
	}, nil
}
