// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/Xwudao/neter-template/pkg/config"
	"github.com/Xwudao/neter-template/pkg/logger"
)

// Injectors from wire.go:

func CmdApp() (*App, func(), error) {
	koanf, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, err := logger.NewLogger(koanf)
	if err != nil {
		return nil, nil, err
	}
	app := NewApp(sugaredLogger, koanf)
	return app, func() {
	}, nil
}

func TestApp() (*TestManager, func(), error) {
	koanf, err := config.NewTestConfig()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, err := logger.NewLogger(koanf)
	if err != nil {
		return nil, nil, err
	}
	appContext := NewTestAppContext()
	testManager := NewTestApp(sugaredLogger, appContext, koanf)
	return testManager, func() {
	}, nil
}
