// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PrefixUsersColumns holds the columns for the "prefix_users" table.
	PrefixUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "user"},
	}
	// PrefixUsersTable holds the schema information for the "prefix_users" table.
	PrefixUsersTable = &schema.Table{
		Name:       "prefix_users",
		Columns:    PrefixUsersColumns,
		PrimaryKey: []*schema.Column{PrefixUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PrefixUsersTable,
	}
)

func init() {
	PrefixUsersTable.Annotation = &entsql.Annotation{
		Table: "prefix_users",
	}
}
